/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-03-28 16:50:24 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/am-fx -t currencies -s am-fx
 *
 */


export namespace currenciesFields {
  export type id = number;
  export type name = string;
  export type rate = number;
  export type code = string;
  export type date_set = Date;
  export type deleted = number;

}

export interface currencies {
  id: currenciesFields.id;
  name: currenciesFields.name;
  rate: currenciesFields.rate;
  code: currenciesFields.code;
  date_set: currenciesFields.date_set;
  deleted: currenciesFields.deleted;

}
