/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-03-28 16:49:55 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/am-fx -t organisation -s am-fx
 *
 */


export namespace organisationFields {
  export type id = number;
  export type code = string;
  export type name = string;
  export type password = string;
  export type location = string;
  export type license_number = string;
  export type email = string;
  export type phone = string;
  export type activated = number;
  export type deleted = number;
  export type created = Date;

}

export interface organisation {
  id: organisationFields.id;
  code: organisationFields.code;
  name: organisationFields.name;
  password: organisationFields.password;
  location: organisationFields.location;
  license_number: organisationFields.license_number;
  email: organisationFields.email;
  phone: organisationFields.phone;
  activated: organisationFields.activated;
  deleted: organisationFields.deleted;
  created: organisationFields.created;

}
