/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-03-28 16:49:29 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/am-fx -t transactions -s am-fx
 *
 */


export namespace transactionsFields {
  export type id = number;
  export type timestamp = Date;
  export type receipt_id = string;
  export type type = string;
  export type currency = string;
  export type amount = number;
  export type rate = number;
  export type full_name = string;
  export type id_number = string;
  export type id_type = string;
  export type home_country = string;
  export type residential_address = string | null;
  export type post_address = string;
  export type teller_id = number;
  export type deleted = number;

}

export interface transactions {
  id: transactionsFields.id;
  timestamp: transactionsFields.timestamp;
  receipt_id: transactionsFields.receipt_id;
  type: transactionsFields.type;
  currency: transactionsFields.currency;
  amount: transactionsFields.amount;
  rate: transactionsFields.rate;
  full_name: transactionsFields.full_name;
  id_number: transactionsFields.id_number;
  id_type: transactionsFields.id_type;
  home_country: transactionsFields.home_country;
  residential_address: transactionsFields.residential_address;
  post_address: transactionsFields.post_address;
  teller_id: transactionsFields.teller_id;
  deleted: transactionsFields.deleted;

}
