/* tslint:disable */


        /**
         * AUTO-GENERATED FILE @ 2019-03-28 16:47:02 - DO NOT EDIT!
         *
         * This file was automatically generated by schemats v.3.0.3
         * $ schemats generate -c mysql://username:password@localhost/am-fx -s public
         *
         */

