/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-03-28 16:48:36 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/am-fx -t users -s am-fx
 *
 */


export namespace usersFields {
  export type id = number;
  export type first_name = string;
  export type last_name = string;
  export type email = string;
  export type organisation_code = string;
  export type role = string;
  export type activated = string;
  export type created = Date;

}

export interface users {
  id: usersFields.id;
  first_name: usersFields.first_name;
  last_name: usersFields.last_name;
  email: usersFields.email;
  organisation_code: usersFields.organisation_code;
  role: usersFields.role;
  activated: usersFields.activated;
  created: usersFields.created;

}
